name: Terraform Apply
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: prayog22/prayog@main
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
