name: Terraform Apply
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: terraform-plan
        uses: dflook/terraform-plan@v1.29.1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Terraform Destroy 
        run: terraform destroy -auto-approve
