name: "Terraform GitHub Actions"
on:
   push: 
    braches:
     - main
jobs: 
    terraform-apply:
      runs-on: ubuntu/latest
      steps:
          - uses: prayog22/Prayog@master
          - name: Terraform Init
            run: terraform init
          - name: Terraform Apply
            run: terraform apply --auto-approve
          env: 
            GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}   
